name: Build KernelSU Exynos9810

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y bc bison flex libfl-dev libssl-dev libelf-dev build-essential curl git

    - name: Clone Toolchain
      run: |
        git clone --depth=1 https://github.com/theradcolor/aarch64-linux-gnu -b stable-gcc toolchain

    - name: Add KernelSU Next + susfs
      run: |
        curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -
        curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next-susfs/kernel/setup.sh" | bash -s next-susfs

    - name: Build Kernel
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export CROSS_COMPILE=$(pwd)/toolchain/bin/aarch64-linux-gnu-
        make exynos9810_defconfig
        make -j$(nproc) V=2

    - name: Package into Flashable ZIP
      run: |
        git clone https://github.com/osm0sis/AnyKernel3.git
        cp arch/arm64/boot/Image.gz-dtb AnyKernel3/zImage
        cd AnyKernel3
        zip -r9 ../KernelSU_Flashable.zip *

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: KernelSU_ZIP
        path: KernelSU_Flashable.zip
